org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
kotlin.mpp.enableCInteropCommonization=true
org.jetbrains.compose.experimental.uikit.enabled=true
# Use a recent Gradle version compatible with plugins
# This property might be better in gradle-wrapper.properties but setting it here for now.
# gradle.distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
